version: '3'

networks:
  clean-sp-net:
    driver: bridge

volumes:
  clean-sp-pg:
    driver: local

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=clean_starterkit
      - TZ=UTC
      - PGTZ=UTC
    ports:
      - 5432:5432
    networks:
      - clean-sp-net
    volumes:
      - clean-sp-pg:/var/lib/postgresql/data
